[package]
name = "enotation"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.5.0", features = ["concolor"] }
num = "0.4.3"
pest = "2.7.15"
pest_derive = "2.7.15"
serde = "1.0.217"
